services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stage-backend
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ./backend/.env
    # Sem portas expostas externamente (comunica via rede interna do docker)
    expose:
      - "3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stage-frontend
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ORIGIN=https://estagio.getmais.com.br
    # Sem portas expostas externamente (comunica via rede interna do docker)
    expose:
      - "3000"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: stage-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
